name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip build-essential python3-pip python3-dev autoconf libtool pkg-config zlib1g-dev libncursesw5-dev libssl-dev libffi-dev libsqlite3-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libgl1-mesa-dev libgles2-mesa-dev libpng-dev libjpeg-dev

      - name: Install Buildozer and Cython
        run: |
          pip3 install --user --upgrade buildozer cython

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:~/.local/bin/
          # Lệnh build chuyên dụng để tránh lỗi Broken Pipe
          buildozer android debug
