name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          # Cấp quyền sudo để cài đặt các thư viện hệ thống tầng thấp
          sudo apt-get install -y git zip unzip build-essential autoconf libtool pkg-config zlib1g-dev libncursesw5-dev libssl-dev libffi-dev libsqlite3-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libgl1-mesa-dev libgles2-mesa-dev libpng-dev libjpeg-dev

      - name: Install Buildozer
        run: |
          # Dùng sudo để cài buildozer vào thư mục hệ thống
          sudo pip3 install --upgrade buildozer cython

      - name: Build APK with Superuser Rights
        run: |
          export PATH=$PATH:~/.local/bin/
          # Lệnh yes | sudo dùng để thực thi build với quyền cao nhất
          # Thêm biến môi trường để ép không hỏi xác nhận
          yes | sudo buildozer -v android debug

      - name: Fix Permissions and Upload
        run: |
          # Cấp quyền đọc cho file APK trước khi upload
          sudo chmod 777 bin/*.apk
          ls -l bin/
        if: always()

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: RootChecker_APK
          path: bin/*.apk
