name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip build-essential autoconf libtool pkg-config zlib1g-dev libncursesw5-dev libssl-dev libffi-dev libsqlite3-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libgl1-mesa-dev libgles2-mesa-dev libpng-dev libjpeg-dev

      - name: Install Buildozer
        run: |
          pip3 install --user --upgrade buildozer cython

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin/
          # Bỏ lệnh clean, chạy thẳng buildozer với -v (verbose) để theo dõi quá trình
          yes | buildozer -v android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: RootChecker_APK
          path: bin/*.apk
